name: finance_os
description: "Finance OS Flutter Mobile App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  injectable: ^2.3.2
  go_router: ^12.1.3
  dio: ^5.4.0
  retrofit: 4.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  connectivity_plus: ^5.0.2
  shimmer: ^3.0.0
  fl_chart: ^0.65.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  retrofit_generator: 8.1.0
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
